services:
  documentx:
    build: .
    expose:
      - "80"
    environment:
      - SECRETS_JSON=${SECRETS_JSON}
    volumes:
      - documentx-cache:/etc/documentx
    networks:
      - dokploy-network
      - default

volumes:
  documentx-cache:

networks:
  dokploy-network:
    external: true
